mobile score will upload and dektop score will be in temporary

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -75,57 +75,60 @@ jobs:
         env:
           LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
 
-  lighthouse-score:
-    needs: build
-    runs-on: self-hosted
-    defaults:
-      run:
-        shell: bash
-        working-directory: app
-
-    steps:
-      - name: checkout code
-        uses: actions/checkout@v4
-        timeout-minutes: 5
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        timeout-minutes: 5
-      
-      
-      - name: setup-node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16
-          cache-dependency-path: ./app/package-lock.json
-        timeout-minutes: 5
-
-
-      - name: install node_modules
-        run: npm install
-
-      - name: copy env
-        run: cp .env.staging .env
-
-      - name: webpack build
-        run: npm run webpack:build
-
-      - name: static generate
-        run: npm run generate
-      
-      - run: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
-      - name: setup-chrome
-        uses: browser-actions/setup-chrome@v1
-        id: setup-chrome
-        with:
-          chrome-version: 122
-
-      - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
-
-      - name: install lighthouse-ci 
-        run: sudo npm install -g @lhci/cli@0.13.x
-
       - name: lighthouse-ci for mobile
         run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
-        env:
-          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}
+        
+  # lighthouse-score:
+  #   needs: build
+  #   runs-on: self-hosted
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: app
+
+  #   steps:
+  #     - name: checkout code
+  #       uses: actions/checkout@v4
+  #       timeout-minutes: 5
+
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #       timeout-minutes: 5
+      
+      
+  #     - name: setup-node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16
+  #         cache-dependency-path: ./app/package-lock.json
+  #       timeout-minutes: 5
+
+
+  #     - name: install node_modules
+  #       run: npm install
+
+  #     - name: copy env
+  #       run: cp .env.staging .env
+
+  #     - name: webpack build
+  #       run: npm run webpack:build
+
+  #     - name: static generate
+  #       run: npm run generate
+      
+  #     - run: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
+  #     - name: setup-chrome
+  #       uses: browser-actions/setup-chrome@v1
+  #       id: setup-chrome
+  #       with:
+  #         chrome-version: 122
+
+  #     - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
+
+  #     - name: install lighthouse-ci 
+  #       run: sudo npm install -g @lhci/cli@0.13.x
+
+  #     - name: lighthouse-ci for mobile
+  #       run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
+  #       env:
+  #         LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}
