PR number printed

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -22,31 +22,31 @@ jobs:
         uses: actions/checkout@v4
         timeout-minutes: 5
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        timeout-minutes: 5
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
+      #   timeout-minutes: 5
       
       
-      - name: setup-node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16
-          cache-dependency-path: ./app/package-lock.json
-        timeout-minutes: 5
+      # - name: setup-node
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 16
+      #     cache-dependency-path: ./app/package-lock.json
+      #   timeout-minutes: 5
 
 
-      - name: install node_modules
-        run: npm install
+      # - name: install node_modules
+      #   run: npm install
 
-      - name: copy env
-        run: cp .env.staging .env
+      # - name: copy env
+      #   run: cp .env.staging .env
 
-      - name: webpack build
-        run: npm run webpack:build
+      # - name: webpack build
+      #   run: npm run webpack:build
 
-      - name: static generate
-        run: npm run generate
-
+      # - name: static generate
+      #   run: npm run generate
+######################
       # - name: upload artifacts
       #   uses: actions/upload-artifact@v4
       #   with:
@@ -58,34 +58,37 @@ jobs:
       #   with:
       #     github_token: ${{ secrets.GITHUB_TOKEN }}
       #     publish_dir: ./app/public
-      - run: sudo apt-get update && sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
+#####################
 
-      - name: setup-chrome
-        uses: browser-actions/setup-chrome@v1
-        id: setup-chrome
-        with:
-          chrome-version: 122
+      # - run: sudo apt-get update && sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
 
-      - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
+      # - name: setup-chrome
+      #   uses: browser-actions/setup-chrome@v1
+      #   id: setup-chrome
+      #   with:
+      #     chrome-version: 122
 
-      - name: install lighthouse-ci 
-        run: sudo npm install -g @lhci/cli@0.13.x
+      # - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
 
-      - name: lighthouse-ci for desktop    
-        run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
-        env:
-          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
+      # - name: install lighthouse-ci 
+      #   run: sudo npm install -g @lhci/cli@0.13.x
 
-      - name: lighthouse-ci for mobile
-        run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
+      # - name: lighthouse-ci for desktop    
+      #   run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
+      #   env:
+      #     LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
+
+      # - name: lighthouse-ci for mobile
+      #   run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
         
+      - run: echo "PR_NUMBER= ${{github.event.number}}"
       - name: Comment PR with lighthouse-ci report
         uses: thollander/actions-comment-pull-request@v2
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           message: |
             report available at http://164.52.192.158:30011
-          pr_number: 198
+          pr_number: ${{github.event.number}}
           comment_tag: live_site_url
   # lighthouse-score:
   #   needs: build
