sepate autorun command for mobile and desktop

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -63,10 +63,15 @@ jobs:
 
       - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
 
-      - name: lighthouse-ci
-        run: |
-          sudo npm install -g @lhci/cli@0.13.x
-          lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!" 
-          lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
+      - name: install lighthouse-ci 
+        run: sudo npm install -g @lhci/cli@0.13.x
+
+      - name: lighthouse-ci for mobile
+        run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}
+
+      - name: lighthouse-ci for desktop    
+        run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
         env:
           LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
