lhci and lighthouseci file added

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -5,7 +5,7 @@ name: staging
 # or API.
 on:
   push:
-    branches: ["main"]
+    # branches: ["main"]
   workflow_dispatch:
 
 jobs:
@@ -22,10 +22,18 @@ jobs:
         uses: actions/checkout@v4
         timeout-minutes: 5
 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        timeout-minutes: 5
+      
+      
       - name: setup-node
         uses: actions/setup-node@v3
         with:
           node-version: 16
+          cache-dependency-path: ./app/package-lock.json
+        timeout-minutes: 5
+
 
       - name: install node_modules
         run: npm install
@@ -39,8 +47,89 @@ jobs:
       - name: static generate
         run: npm run generate
 
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
+      # - name: upload artifacts
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: build-context
+      #     path: ./   
+
+      # - name: Deploy
+      #   uses: peaceiris/actions-gh-pages@v3
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     publish_dir: ./app/public
+      - run: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
+
+      - name: setup-chrome
+        uses: browser-actions/setup-chrome@v1
+        id: setup-chrome
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./app/public
+          chrome-version: 122
+
+      - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
+
+      - name: install lighthouse-ci 
+        run: sudo npm install -g @lhci/cli@0.13.x
+
+      - name: lighthouse-ci for desktop    
+        run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
+        env:
+          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
+
+      - name: lighthouse-ci for mobile
+        run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
+        
+  # lighthouse-score:
+  #   needs: build
+  #   runs-on: self-hosted
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: app
+
+  #   steps:
+  #     - name: checkout code
+  #       uses: actions/checkout@v4
+  #       timeout-minutes: 5
+
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #       timeout-minutes: 5
+      
+      
+  #     - name: setup-node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16
+  #         cache-dependency-path: ./app/package-lock.json
+  #       timeout-minutes: 5
+
+
+  #     - name: install node_modules
+  #       run: npm install
+
+  #     - name: copy env
+  #       run: cp .env.staging .env
+
+  #     - name: webpack build
+  #       run: npm run webpack:build
+
+  #     - name: static generate
+  #       run: npm run generate
+      
+  #     - run: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
+  #     - name: setup-chrome
+  #       uses: browser-actions/setup-chrome@v1
+  #       id: setup-chrome
+  #       with:
+  #         chrome-version: 122
+
+  #     - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
+
+  #     - name: install lighthouse-ci 
+  #       run: sudo npm install -g @lhci/cli@0.13.x
+
+  #     - name: lighthouse-ci for mobile
+  #       run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
+  #       env:
+  #         LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}
