lighthouse steps uncommented

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -22,30 +22,30 @@ jobs:
         uses: actions/checkout@v4
         timeout-minutes: 5
 
-      # - name: Set up Docker Buildx
-      #   uses: docker/setup-buildx-action@v3
-      #   timeout-minutes: 5
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        timeout-minutes: 5
       
       
-      # - name: setup-node
-      #   uses: actions/setup-node@v3
-      #   with:
-      #     node-version: 16
-      #     cache-dependency-path: ./app/package-lock.json
-      #   timeout-minutes: 5
+      - name: setup-node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16
+          cache-dependency-path: ./app/package-lock.json
+        timeout-minutes: 5
 
 
-      # - name: install node_modules
-      #   run: npm install
+      - name: install node_modules
+        run: npm install
 
-      # - name: copy env
-      #   run: cp .env.staging .env
+      - name: copy env
+        run: cp .env.staging .env
 
-      # - name: webpack build
-      #   run: npm run webpack:build
+      - name: webpack build
+        run: npm run webpack:build
 
-      # - name: static generate
-      #   run: npm run generate
+      - name: static generate
+        run: npm run generate
 ######################
       # - name: upload artifacts
       #   uses: actions/upload-artifact@v4
@@ -60,42 +60,34 @@ jobs:
       #     publish_dir: ./app/public
 #####################
 
-      # - run: sudo apt-get update && sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
+      - run: sudo apt-get update && sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
 
-      # - name: setup-chrome
-      #   uses: browser-actions/setup-chrome@v1
-      #   id: setup-chrome
-      #   with:
-      #     chrome-version: 122
+      - name: setup-chrome
+        uses: browser-actions/setup-chrome@v1
+        id: setup-chrome
+        with:
+          chrome-version: 122
 
-      # - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
+      - run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
 
-      # - name: install lighthouse-ci 
-      #   run: sudo npm install -g @lhci/cli@0.13.x
+      - name: install lighthouse-ci 
+        run: sudo npm install -g @lhci/cli@0.13.x
 
-      # - name: lighthouse-ci for desktop    
-      #   run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
-      #   env:
-      #     LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
-
-      # - name: lighthouse-ci for mobile
-      #   run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
-        
-      - name: Get Pull Request Number
-        id: pr
-        run: echo "pull_request_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT
+      - name: lighthouse-ci for desktop    
+        run: lhci autorun --config ../.lighthouserc.js --collect.settings.preset=desktop --upload.target=temporary-public-storage || echo "LHCI failed!" 
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_APP_TOKEN }}  
 
-      - run: echo ${{ steps.pr.outputs.pull_request_number }}
+      - name: lighthouse-ci for mobile
+        run: lhci autorun --config ../.lighthouserc.js || echo "LHCI failed!"
 
       - uses: jwalton/gh-find-current-pr@master
         id: findPr
 
-      - run: echo "Your PR is ${PR}"
-        if: success() && steps.findPr.outputs.number
-        env:
-          PR: ${{ steps.findPr.outputs.pr }}      
+      # - run: echo "Your PR is ${PR}"
+      #   if: success() && steps.findPr.outputs.number
+      #   env:
+      #     PR: ${{ steps.findPr.outputs.pr }}      
       - name: Comment PR with lighthouse-ci report
         uses: thollander/actions-comment-pull-request@v2
         with:
